### PR TITLE
Combined pull request

### PR DESCRIPTION
**Pull request by benzkji**
All my proposals are quite small...here, they are combined in one pull request. Open for enhancements and comments. I'm currently using this branch in my projects.

**Changes** 
- `content` field not required in admin form
- "show key" changes, as in #5 
- admin enhancements: added search fields, made `key` a readonly field, filter by content type.
- made `key` a CharField
- update cache mode (using a hash for cache key) so there is no problem with special or control chars in keys.
- implent a fallback, when no request object is in the received contex

### CODE REVIEW

**Comment by fabiangermann** [comment]
You've been busy :)

Thank you. The only problem I have is with issue #7. This introduces a breaking change because the textblock-key is used in the cache-key and some cache backends (e.g. Memcached) are not so liberal with their requirements for a cache key (e.g. no whitespace). So that's why the key is a slug field.

I quickly thought about slugifying (when generating the cache key) but that could possibly result in duplicate keys and very disturbing and inexplicable behavior. So at the moment I don't really see any way around it.

**Comment by fabiangermann** [comment]
Actually I do see a way, but it requires more code. I guess we could allow activating String-keys via a `TEXTBLOCKS_KEY_STRING_VALIDATION`-setting. This way a developer can activate it if he knows the backend does support it. The validation of the field would have to use slug-field behavior if if the setting is set, and normal string behavior otherwise.

If  you're not in a hurry and can work with your current fork I will have a look at it when making a new release.

**Comment by benzkji** [comment]
actually, we should ensure the validation takes place when textblocks are added when hit in a template (not validated, but just run through slugify?). ATM I can easily have keys with special chars and whitespace - but cannot edit those later on in the admin, because of validation ;-)

And yes, enabling string mode with a setting is a good solution as well.

Another thought: instead of slugifying the key for the cache key, using a sha or any other hash of the key could be used as cache key? Like this, it could just work? ;-)

**Comment by benzkji** [comment]
Hi again. What do you think of that hash solution? If ok, I could then go ahead and update this pull request accordingly.

**Comment by fabiangermann** [comment]
Hey!

Sry, was not in the office yesterday. I think the hashing should work just fine. Good idea! The only downside is that the hash key is not reversible this way. But I cant think of a reason why that should matter. Maybe just hash the textblock-key and leave the prefix of the cache key as it is. So one could clear all textblock cache entries without clearing the whole shared cache.

**Comment by benzkji** [comment]
easy. also, open source...
yes, always prefix! I'll go ahead :-)

**Comment by benzkji** [comment]
so, would you drop the slugify mode completly? I see no reason to keep it, if we use a hash? as I see it now, this would not break anything?

**Comment by fabiangermann** [comment]
Absolutely. The hashing basically is the slugifying. Besides, slugifying (at least with the django function) could result in non-unique keys again.

**Comment by benzkji** [comment]
ok perfect. makes it much easier. I've added an overview above, what I've done so far, so there is no bad surprise for you ;-)

**Comment by benzkji** [comment]
done. please, test it.

some basic unit tests and an integrated testproject would be nice as well. atm I always need to think which real world project could be used for testing/developing...or setup a testproject...anyway, thx for being reactive, and hoping for a release...dont like those `-e` in my requirements ;-)

**Comment by fabiangermann** [comment]
Thank you!

I'll add an AUTHORS File to the project and include you (unless you don't want that of course). I'll also update the readme and maybe add some tests if I can squeeze it in. So it may take a little but I'll try to do it asap.

**Comment by benzkji** [comment]
nice, thx for the release!

**Pull request merged**
