### PR TITLE
WIP: first version with show_key

### PR DESCRIPTION
**Pull request by benzkji**
let me know what you think. the boolean is quite hacky, open for better solutions (the problem: [here](http://stackoverflow.com/questions/4557114/django-custom-template-tag-which-accepts-a-boolean-parameter))

(added .idea to gitignore, for pycharm)

### CODE REVIEW

**Comment by benzkji** [comment]
concerning #4

**Comment by fabiangermann** [comment]
Thank you!

Yes the boolean in template tags is always a little tedious. I usually do it by passing 0 or 1 (so it's False if a zero is passed and True for everything else). I'm not quite sure what you intended to pass for the show_key-parameter?

Maybe I just don't understand it but I think the if-clause in the end can be much simpler:

```python
def textblock(context, key, type, show_key=0):
    ...

    if not text and (show_key or conf.TEXTBLOCKS_SHOWKEY):
        text = textblock.key
```

If `text` has no value and either `show_key` or the setting is True (or 1 or whatever) the key will be displayed.

**Comment by benzkji** [comment]
not really

    if not text and (show_key or conf.TEXTBLOCKS_SHOWKEY):
        text = textblock.key

if `TEXTBLOCKS_SHOWKEY` is `True`, your code will show the key, even if I explicitly pass `0` to the tag. I'm not quite happy with that code neither, but found no other solution...if I put everything in one `if`, it gets even messier.

**Comment by fabiangermann** [comment]
Of course, you're right. Was not thinking it through properly ;).

Thank you! I'll try to make a new release shortly.

**Comment by benzkji** [comment]
cool, thx!

**Pull request closed without merging**
